### PR TITLE
Ingress extclient page updates

### PR DESCRIPTION
**Pull request by cameronts**

### CODE REVIEW

**Comment by afeiszli** [comment]
Please include information about how to enable/disable ext clients in this section.

**Comment by afeiszli** [comment]
Additionally, please note the following on configuring DNS: By default, netmaker will forward all DNS requests to the server. If you want to use an external or private DNS server, you need to change the following config:

PORT_FORWARD_SERVICES="dns" --> PORT_FORWARD_SERVICES=""

**Review by afeiszli — CHANGES_REQUESTED** [review]
please add requested changes ahead of approval

**Comment by cameronts** [comment]
> Please include information about how to enable/disable ext clients in this section.

Delete and re-add?  Or WireGuard steps for the interface down/up on the client machine?

**Review by cameronts — COMMENTED** [review]
Changes addressed please re-review

**Review by afeiszli — APPROVED** [review]

**Pull request merged**
